#Project information
site_name: Ivan's MkDocs site
site_url: https://ivancheban.github.io/my-mkdocs/
site_author: Ivan Cheban
theme: material
#Repo info
repo_name: my-mkdocs
repo_url: https://ivancheban.github.io/my-mkdocs

nav:
- Intro: index.md
